version: '3'

services:
  python:
    build:
      context: ./
    volumes:
      - ./notes/:/opt/notebooks/
    command: bash -c "jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"
    ports:
      - 8888:8888
